# Generated by Django 3.2.9 on 2021-12-09 09:55

import core.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(default=datetime.date.today, validators=[core.validators.AdultValidator(21)]),
        ),
    ]
