# Generated by Django 4.0 on 2021-12-22 07:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('age', models.IntegerField()),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('salary', models.PositiveIntegerField(default=1500)),
                ('specialization', models.CharField(max_length=100)),
                ('work_experience', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
