# Generated by Django 3.2.9 on 2021-12-09 07:31

from django.db import migrations, models
import core


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True,
        ))
    ]
