# Generated by Django 3.2.9 on 2021-12-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('start_date', models.DateField(default='19.10.2021')),
                ('number_of_students', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=50)),
            ],
        ),
    ]
