# Generated by Django 4.0 on 2021-12-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_group_number_of_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='course_name',
            new_name='group_name',
        ),
    ]
