# Generated by Django 4.0 on 2021-12-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacher_name',
        ),
    ]
